### ISSUE TITLE
Investigate TFrecord or other input modalities

### ISSUE THREAD

**Issue by grewe** [grewe/covid_id_detection_base#3]
Emmanuel + Lynne - modify current code to read ALL images from the file and try to to find resources on using TFRecord for input 

---> NOTE:[ separate issue for LabelImage.pbtxt and not hard coded #classes,etc.
](https://github.com/grewe/covid_id_detection_base#workspaces/covid-id-object-detection-tf2-5f1604ffdb748200104dbeba/board?repos=281202141)

- [for obj. detcion api tf2 main page](https://blog.tensorflow.org/2020/07/tensorflow-2-meets-object-detection-api.html?m=1)
- [for mini example jupyter notebook](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0)
- [***LYNNE's Modified version of mini example***](https://drive.google.com/drive/u/3/folders/1EMiJMe-bsxt0ylWRr6gKQG03U9sqyaIP
)

> [Possible advanced example from TF Issue](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817)

- [Issue posted to Tensorflow & possible advanced instruction--please follow](https://github.com/tensorflow/models/issues/8869)

**Comment by grewe** [comment]
see [https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817)

**Comment by grewe** [comment]
from emmanuel ...copying here to correct issue


IMPORTANT 1: IN FOLLOWING BLOCK NOTICE URL YOU SHOULD USE 
```python
#Downloading data from Roboflow
#UPDATE THIS LINK - get our data from Roboflow
%cd /content
!curl -L "https://public.roboflow.ai/ds/gsMulGeT7R?key=5wUiAjdf4Y" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
```


IMPORTANT 2: IN THE NEXT BLOCK NOTICE THIS IS A DIFFERENT URL YOU SHOULD USE
```python
#downloading test images from Roboflow
#export dataset above with format COCO JSON
#or import your test images via other means. 
%mkdir /content/test/
%cd /content/test/
!curl -L "https://public.roboflow.ai/ds/it2aZZ4A4j?key=S68L0Yct87" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
```

**Comment by grewe** [comment]
Note in using the colab at https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817  and modifying it for local use --there is an error in keras library that is fixed.  Specifically the tensorflow/python/keras/utils/tf_utils.py is overwritten with changes.    So this file must be found locally on the machine you are running your Jupyter notebook on.   If running in environment like Anaconda then need to find the correct path.  I have a tf2_ObDet environment defined on my Anaconda and I THINK the equivalent environment might be
C:\Users\Lynne\Anaconda3\envs\tf2_ObDet\Lib\site-packages\tensorflow\python\keras\utils  (NOTE: this is the one that was date stamped corresponding to running the cell at top of notebook saying 
- !pip install -U --pre tensorflow=="2.*" 


But there are other possbilitiees like:

 C:\Users\Lynne\Anaconda3\pkgs\tensorflow-base-2.1.0-eigen_py37h49b2757_0\Lib\site-packages\tensorflow_core\python\keras\utils

**Comment by grewe** [comment]
TWO ISSUES

**ISSUE 1: had errors trying to import model_builder  using line of code in jupyter notebook:
`from object_detection.builders import model_builder`**
 
  **get error** :  
_```

> `AttributeError                            Traceback (most recent call last)
>  <ipython-input-5-f1e1865988e2> in <module>
>       25 #NOTE: had to comment out the following two lines as had errors???
>       26 #from object_detection.utils import colab_utils
>  ---> 27 from object_detection.builders import model_builder
>       28 
>       29 get_ipython().run_line_magic('matplotlib', 'inline')
>  
>  C:\tensorflow\models\research\object_detection\builders\model_builder.py in <module>
>       17 from object_detection.builders import anchor_generator_builder
>       18 from object_detection.builders import box_coder_builder
>  ---> 19 from object_detection.builders import box_predictor_builder
>       20 from object_detection.builders import hyperparams_builder
>       21 from object_detection.builders import image_resizer_builder
> 
>  C:\tensorflow\models\research\object_detection\builders\box_predictor_builder.py in <module>
>       16 """Function to build box predictor from configuration."""
>       17 
>  ---> 18 from object_detection.core import box_predictor
>       19 from object_detection.protos import box_predictor_pb2
>       20 
>  
>  C:\tensorflow\models\research\object_detection\core\box_predictor.py in <module>
>       34 from object_detection.utils import static_shape
>       35 
>  ---> 36 slim = tf.contrib.slim
>       37 
>       38 BOX_ENCODINGS = 'box_encodings'
>  AttributeError: module 'tensorflow' has no attribute 'contrib`



**Posted issue:**
[https://github.com/tensorflow/models/issues/8941](https://github.com/tensorflow/models/issues/8941)

**ISSUE 2: had issues running from command line (or origially jupyter notbeook) the model_builder_tf2_test.py file and posted issue**

`python model_builder_tf2_test.py`

**get error:**
`
2020-07-22 14:51:52.010661: 
tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-22 14:51:52.017378: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 19, in <module>
    from object_detection.builders import box_predictor_builder
  File "C:\tensorflow\models\research\object_detection\builders\box_predictor_builder.py", line 18, in <module>
    from object_detection.core import box_predictor
  File "C:\tensorflow\models\research\object_detection\core\box_predictor.py", line 36, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'`

[https://github.com/tensorflow/models/issues/8942](https://github.com/tensorflow/models/issues/8942)****
